#! /usr/bin/env ruby

require_relative "../scripts/utils/cli"

$stderr.puts("Running pre-push validation...\n\n")

lines = `git fetch origin main 2> /dev/null && git diff --name-only origin/main | grep -E "\.rbi$|index.json"`.lines
files = lines.map(&:strip).select { |file| File.file?(file) }
rbis = files.select { |file| File.extname(file) === ".rbi"}

if lines.empty?
  $stderr.puts("Nothing to check")
  $stderr.puts("\n")
  exit(0)
end

unless system("scripts/check_all #{rbis.join(" ")}")
  $stderr.puts("\nSome checks have failed, cancelling the push (see above)".red)
  exit(1)
end

$stderr.puts("\n")
exit(0)
