#! /usr/bin/env ruby

$stderr.puts("Running pre-push validation...")

lines = `git fetch origin main 2> /dev/null && git diff --name-only origin/main | grep -E "\.rbi$|index.json"`.lines
files = lines.map(&:strip).select { |file| File.file?(file) }
rbis = files.select { |file| File.extname(file) === ".rbi"}

if lines.empty?
  $stderr.puts("Nothing to check")
  $stderr.puts("\n")
  exit(0)
end

success = true

unless rbis.empty?
  $stderr.puts("Linting RBI files...")
  unless system("bundle exec rubocop #{rbis.join(" ")}")
    success = false
  end
  $stderr.puts("Type checking RBI files...")
  unless system("scripts/check_types #{rbis.join(" ")}")
    success = false
  end
  $stderr.puts("Checking that new RBI files belong to public gems...")
  unless system("scripts/check_gems_are_public #{rbis.join(" ")}")
    success = false
  end
  $stderr.puts("Checking RBI files against runtime execution...")
  unless system("scripts/check_runtime #{rbis.join(" ")}")
    success = false
  end

  $stderr.puts("Checking RBI files against Tapioca and Sorbet...")
  unless system("scripts/check_static #{rbis.join(" ")}")
    success = false
  end
end

$stderr.puts("Checking index.json...")
unless system("scripts/check_index")
  success = false
end

unless success
  $stderr.puts("Cancelling the push as the code fails at least one check (see above)")
  exit(1)
end

$stderr.puts("\n")
exit(0)
