name: rbi-central

type: ruby

up:
  - ruby: '3.1'
  - bundler

commands:
  test:      "scripts/check_types"
  style:     "bundle exec rubocop"
  style-fix: "bundle exec rubocop -a"
  sanity:    "scripts/check_types && bundle exec rubocop"
