#! /usr/bin/env ruby

require "rbi-central"

success = true

$stderr.puts("### Checking index...".bold.blue)
$stderr.puts
success &= system("scripts/check_index")

files = RBICentral.rbi_files.join(" ")
unless files.empty?
  $stderr.puts
  $stderr.puts("### Linting RBI files...".bold.blue)
  $stderr.puts
  success &= system("bundle exec rubocop #{files}")

  $stderr.puts
  $stderr.puts("### Checking that all RBI files belong to public gems...".bold.blue)
  $stderr.puts
  success &= system("bundle exec check_gems_are_public #{files}")

  $stderr.puts
  $stderr.puts("### Checking RBI files against runtime execution...".bold.blue)
  $stderr.puts
  success &= system("bundle exec check_runtime #{files}")

  $stderr.puts
  $stderr.puts("### Checking RBI files against Tapioca and Sorbet...".bold.blue)
  $stderr.puts
  success &= system("bundle exec check_static #{files}")
end

exit(success)
