# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-sorbet

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
  - "vendor/**/*"

Naming/FileName:
  Exclude:
  - "lib/rbi-central.rb"

Sorbet:
  Enabled: true

Sorbet/TrueSigil:
  Enabled: true
  Exclude:
  - "**/minitest.rbi"


Sorbet/StrictSigil:
  Enabled: true
  Exclude:
  - "test/rbi-central/**/*.rb"
