# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group(:development, :test) do
  gem("minitest")
  gem("minitest-reporters")
  gem("rake", "~> 13.0")
  # TODO: remove once contexts are released
  gem("spoom", github: "Shopify/spoom", branch: "main")
end
