name: CI

on: [push, pull_request]

env:
  GIT_DEFAULT_BRANCH: ${{github.event.repository.default_branch}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          bundler-cache: true
      - name: Check RBIs and index
        run: |
          git fetch origin "$GIT_DEFAULT_BRANCH"
          bundle exec repo check --gem --ref "origin/$GIT_DEFAULT_BRANCH"
